controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true
 
    four_wheel_steering_controller:
      type: four_wheel_steering_controller/FourWheelSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster




joint_state_broadcaster:
  ros__parameters:

    publish_rate: 50


four_wheel_steering_controller:
  ros__parameters:

    front_wheel: ['front_left_wheel_joint', 'front_right_wheel_joint']
    rear_wheel: ['rear_left_wheel_joint', 'rear_right_wheel_joint']
    front_steering: ['front_left_wheel_steering_joint', 'front_right_wheel_steering_joint']
    rear_steering: ['rear_left_wheel_steering_joint', 'rear_right_wheel_steering_joint']
    publish_rate: 50.0
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    velocity_rolling_window_size: 10
    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    # wheel_separation : 0.122
    wheel_separation_h : 0.36
    wheel_separation_w : 0.34317
    wheel_radius : 0.09
    wheel_steering_y_offset : -0.1
    # wheel_steering_x_offset : 0.03

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier    : 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 1.0
    
    # Base frame_id
    # base_frame_id: base_footprint #default: base_link
    base_frame_id: base_link

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.667  # m/s
        min_velocity           : -1.667 # m/s
        has_acceleration_limits: true
        max_acceleration       : 1.0  # m/s^2
        min_acceleration       : -1.0 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 3.14  # rad/s
        min_velocity           : -3.14
        has_acceleration_limits: true
        max_acceleration       : 1.0  # rad/s^2
        min_acceleration       : -1.0

    /gazebo_ros_control:
      pid_gains:
        fl_steering_wheel:
          p: 300
          i: 0
          d: 10
        fr_steering_wheel:
          p: 300
          i: 0
          d: 10
        rl_steering_wheel:
          p: 300
          i: 0
          d: 10
        rr_steering_wheel:
          p: 300
          i: 0
          d: 10
        fl_wheel: #front_left_wheel
          p: 10.0
          i: 1
          d: 0.0
        fr_wheel: #front_right_wheel
          p: 10.0
          i: 1
          d: 0.0
        rl_wheel: #rear_left_wheel
          p: 10.0
          i: 1
          d: 0.0
        rr_wheel: #rear_right_wheel
          p: 10.0
          i: 1
          d: 0.0
      
